/*
     AUTHOR: KHURAM HASEEB
    SUMMARY: ITS AUTHENTICATION CONST FILE THAT HAVE DEFAULT DEFINE VARIABLES USED
             IN DIFFERENT ACTION,SAGA,REDUCER FILE TO PERFORM SPECIFIC FUNCTION.
*/

// EXPORT DEFAULT FOR AUTHENTICATION CONSTANT
export default
    {
        // VARIABLE OF THE PRIVACY REQUEST
        GET_PRIVACY_REQUEST: "GET_PRIVACY_REQUEST",
        GET_PRIVACY_SUCCESS: "GET_PRIVACY_SUCCESS",
        GET_PRIVACY_FAILURE: "GET_PRIVACY_FAILURE",

        // WHEN A USER OPEN THE APP THE STATIC DATA WILL BE LOAD IN THE FRONT END SIDE
        GET_SPLASH_SCREEN_REQUEST: "GET_SPLASH_SCREEN_REQUEST",
        GET_SPLASH_SCREEN_SUCCESS: "GET_SPLASH_SCREEN_SUCCESS",
        GET_SPLASH_SCREEN_FAILURE: "GET_SPLASH_SCREEN_FAILURE",

        // USER VERIFY OTP VARIABLE FOR LOGIN/SIGNUP USER
        VERIFY_OTP_REQUEST: "VERIFY_OTP_REQUEST",
        VERIFY_OTP_SUCCESS: "VERIFY_OTP_SUCCESS",
        VERIFY_OTP_FAILURE: "VERIFY_OTP_FAILURE",

        // GET SIGNUP STATIC DATA LOAD FOR WHOLE APPLICATION
        STATIC_SIGNUP_DATALOAD_REQUEST: "STATIC_SIGNUP_DATALOAD_REQUEST",
        STATIC_SIGNUP_DATALOAD_SUCCESS: "STATIC_SIGNUP_DATALOAD_SUCCESS",
        STATIC_SIGNUP_DATALOAD_FAILURE: "STATIC_SIGNUP_DATALOAD_FAILURE",

        // USER LOGIN WITH FACEBOOK
        ADD_FB_REQUEST: "ADD_FB_REQUEST",
        ADD_FB_SUCCESS: "ADD_FB_SUCCESS",
        ADD_FB_FAILURE: "ADD_FB_FAILURE",

        // USER LOGIN WITH FACEBOOK
        LOGIN_GMAIL_REQUEST: "LOGIN_GMAIL_REQUEST",
        LOGIN_GMAIL_SUCCESS: "LOGIN_GMAIL_SUCCESS",
        LOGIN_GMAIL_FAILURE: "LOGIN_GMAIL_FAILURE",

        //  USER LOGIN WITH FACEBOOK
        LOGIN_APPLE_REQUEST: "LOGIN_APPLE_REQUEST",
        LOGIN_APPLE_SUCCESS: "LOGIN_APPLE_SUCCESS",
        LOGIN_APPLE_FAILURE: "LOGIN_APPLE_FAILURE",

        // USER DATA CONSTANT TYPE
        USER_DATA_REQUEST: "USER_DATA_REQUEST",
        

        // ADDRESS LIST USER DATA
        ADDRESS_LIST_REQUEST: "ADDRESS_LIST_REQUEST",

    }
